#program for the frozen set operations
fs=frozenset({1,2,3})
fz=frozenset({5,6,7})
n=frozenset('manoj kumar')
m=frozenset('panda is a good boy')
print('The first frozen set is {0} and the second frozennset {1}'.format(fs,fz))
print('The Third frozenset is {0} and the fourth frozen set{1}'.format(n,m))
set1=set()
set1.add(fs)
set1.add(fz)
print('The combination of the two frozenset is -->',set1)
set2=set()
set2.add(m)
set2.add(n)
print('The combination of two frozen set that is frozen set3 and frozen set4 is -->',set2)
